version: "3"

services: 
  zed_camera:
    mage: ghcr.io/peterdavidfagan/zed2:humble
    build: 
      context: ../../../../
      dockerfile: .docker/cameras/Dockerfile.zed
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./config/zed2i.yaml:/root/zed_ws/src/cameras/zed_wrapper/config/zed2i.yaml
    devices:
      - "/dev:/dev"
    network_mode: "host"
    privileged: true
    runtime: nvidia
    command: ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zed2i node_name:=zed_camera

  motion_planning_prerequisites:
    image: ghcr.io/peterdavidfagan/panda_motion_planning:humble
    build: 
      context: ../../../../
      dockerfile: .docker/motion_planning/Dockerfile.motion_planning
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tml/.X11-unix:rw
      - ../../applications:/root/panda_ws/src/applications
    network_mode: "host"
    command: ros2 launch panda_motion_planning_demos motion_planning_prerequisites.launch.py

  object_detection:
    image: ghcr.io/peterdavidfagan/object_detection:humble
    container_name: object_detection
    build: 
      context: ../../
      dockerfile: .docker/object_detection/Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - "/dev:/dev"
    privileged: true
    runtime: nvidia
    network_mode: "host"
    command: python3 ./src/object_detection/ros2_object_detection/ros2_object_detection_components/ros2_object_detection_components/grounded_dino.py --topic=/zed/zed_camera/rgb/image_rect_color

  transporter_deployment:
    image: ghcr.io/peterdavidfagan/transporter_deployment:humble
    build: 
      context: ../../../../
      dockerfile: .docker/transporter_deployment/Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tml/.X11-unix:rw
      - ./../../data_collection:/root/data_collection_ws/src/data_collection
      - ./../../motion_planning:/root/data_collection_ws/src/motion_planning
      - ./../../applications:/root/data_collection_ws/src/applications
    network_mode: "host"
    runtime: nvidia
    command: python3 src/applications/transporter_deployment/sort_fruit.py
