version: "3"

services: 
  calibration_app:
    image: ghcr.io/peterdavidfagan/moveit2_camera_calibration:humble
    container_name: moveit2_camera_calibration
    build: 
      context: ../../
      dockerfile: .docker/camera_calibration_app/Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - "/dev:/dev"
    privileged: true
    runtime: nvidia
    network_mode: "host"
    command: python3 ./src/moveit2_camera_calibration/moveit2_camera_calibration/camera_calibration_app.py 
