camera_image_topic: /zed/zed_camera/rgb_raw/image_raw_color
camera_info_topic: /zed/zed_camera/rgb_raw/camera_info

charuco:
  squares_x: 14
  squares_y: 9
  square_length: 0.02
  marker_length: 0.015
  
workspace:
  x_min: -0.1
  x_max: 0.1
  y_min: -0.1
  y_max: 0.1
  z_min: -0.1
  z_max: 0.1
  rot_x_min: -20.0
  rot_x_max: 20.0
  rot_y_min: -20.0
  rot_y_max: 20.0
  rot_z_min: -20.0
  rot_z_max: 20.0

eye_to_hand_calibration:
  num_samples: 50 # for debug purposes
  sample_delay: 0.2

eye_in_hand_calibration:
  num_samples: 50 # for debug purposes
  sample_delay: 0.2
