# config/zed2i_yaml
# Parameters for Stereoabs zed2i camera
---
/**:
    ros__parameters:
        general:
            camera_model: 'zed2i'
            camera_name: 'zed2i' # usually overwritten by launch file
            serial_number: 35215462
            grab_resolution: 'HD2K' # Maximize resolution for calibration
            grab_frame_rate: 30 # ZED SDK internal grabbing rate

        depth:
            min_depth: 0.2 # Min: 0.2, Max: 3.0
            max_depth: 10.0 # Max: 40.0l
