workspace:
  table_height_offset: 0.0

robot:
  ip: 192.168.106.99
  use_fake_hardware: false
  use_gripper: false
  gripper_controller: /robotiq/robotiq_gripper_controller/gripper_cmd
  gripper_tcp_offset: 0.17

camera:
  rgb_topic: /zed/zed_camera/rgb/image_rect_color
  depth_topic: /zed/zed_camera/depth/depth_registered

  intrinsics:
    fx: 523.4645385742188
    fy: 523.4645385742188
    cx: 561.8798828125
    cy: 309.3200378417969   

  extrinsics:
    x: 1.04322964
    y: -0.11564952
    z: 0.84412144
    qx: 0.67835388
    qy: 0.63676566
    qz: -0.22833043
    qw: -0.28675899  

grounded_dino:
  prompts:
    - a red apple
    - a green apple