version: "3"

services: 
  zed2:
    image: ghcr.io/peterdavidfagan/zed2:humble
    build: 
      context: ../../
      dockerfile: .docker/cameras/Dockerfile.zed
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - "/dev:/dev"
    privileged: true
    runtime: nvidia
    network_mode: "host"
    command: ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zedm serial_number:=15102076
    deploy:
      placement:
        constraints:
          - node.hostname == thor
