version: "3"

services: 
  control_server:
    image: ghcr.io/peterdavidfagan/panda_control:iron
    build: 
      context: ../../
      dockerfile: .docker/control/Dockerfile.control
    devices:
      - "/dev:/dev"
    privileged: true
    network_mode: "host"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 70
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
    command: ros2 launch panda_control_demos control_server.launch.py # replace with command for specific tutorial
    deploy:
      restart_policy: 
        condition: any
      placement:
        constraints:
          - node.hostname == robot
