version: "3"

services: 
  foxglove:
    image: ghcr.io/foxglove/studio:latest
    network_mode: "host"
    volumes:
      - ../../.foxglove/mujoco_panda_position.json:/foxglove/default-layout.json
  
  foxglove_bridge:
    image: ghcr.io/peterdavidfagan/foxglove_bridge:rolling
    network_mode: "host"
