title: Toolkit Documentation
description: Guides for performing robot learning research with ROS 2 ecosystem.
theme: just-the-docs

url: https://peterdavidfagan.github.io/ros2_robotics_research_toolkit # this url not being used right now
color_scheme: ros2_robotics_research_toolkit # TODO: update name to DROID

aux_links:
  Official GitHub Repository: https://github.com/peterdavidfagan/ros2_robotics_research_toolkit
